sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env:
        - EXECUTE_CS_CHECK=true
    - php: 7.4

before_install:
  - composer self-update

install:
  - travis_retry composer update --no-interaction

script:
  - vendor/bin/phpunit
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/phpcs ; fi
